spring:
  application:
    name: auth-carvajal-microservice
  cloud:
    consul:
      host: ${CONSUL_URL:localhost}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
        prefer-ip-address: true
        health-check-timeout: 10s
        health-check-critical-timeout: 1m
        heartbeat:
          enabled: true
server:
  port: 4444